#!/bin/sh
###########################
# sendAPRS - Start trying to send APRS position reports over 2m
#
# HISTORICAL INFORMATION -
#
#  2018-02-10  msipin  Created
#  2018-11-01  msipin  Converted from using BCM built-in oscillator to using Baofeng 888
#  2018-11-04  msipin  Put back to using BCM built-in oscillator for Warpig-IV testing
###########################

PATH=.:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pifm
export PATH

# Frequency in Megahertz (Mhz)
#   E.G. 144.390 = Mhz FM (+/- a little offset...?)
##FREQ=144.394157		# Seems (visually on waterfall) properly centered - My and Eric's original "walkabout" tests used this
FREQ=144.392929		# Tests in VVille, after St. Louis, and with replacement board xmitting 1229 Hz too high
#FREQ=144.390		# Did *NOT* get decoded on direwolf...
#FREQ=144.3941		# CF with 0.100 divider may spread the inter-grouping signals out more like the real/live signals appear - St. Louis tests used this!

cd /home/pifm

while [ 1 ]
do
	/home/pifm/makePacket.sh -q

	## Play packet (wav) file out via BCM built-in oscillator
	/home/pifm/pifm /home/pifm/packet.Loc.wav ${FREQ} 44100 mono 4 2>&1 > /dev/null

	## Play packet (wav) file out the PCM0/PCM1 audio output (feeds the Baofeng 888 microphone input)
	##/usr/bin/aplay /home/pifm/packet.Loc.wav 2>&1 > /dev/null

	## LIVE VALUE -
	##sleep 43

	## TEST VALUE -
	sleep 21

done 2>&1 >> /home/pifm/aprs.log

exit 0

