#!/bin/sh
###########################
# sendAPRS - Start trying to send APRS position reports over 2m
#
# HISTORICAL INFORMATION -
#
#  2018-02-10  msipin  Created
#  2018-11-01  msipin  Converted from using BCM built-in oscillator to using Baofeng 888
#  2018-11-04  msipin  Put back to using BCM built-in oscillator for Warpig-IV testing
#  2018-11-06  msipin  Added notes about what we used for "Live Values" for Warpigs III, IV and V
#  2019-01-16  msipin  Switched back to using the Baofeng 888 (Warpigs V, VI and beyond - for 2-way
#                      APRS-based comms!)
#  2019-05-03  msipin  Integrated with Direwolf + kissutil
#  2019-05-16  msipin  Stopped logging to aprs.log (redundant to position reports and GPS/time/temp logs)
###########################

PATH=.:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pifm
export PATH

# Frequency in Megahertz (Mhz)
#   E.G. 144.390 = Mhz FM (+/- a little offset...?)
##FREQ=144.394157		# Seems (visually on waterfall) properly centered - My and Eric's original "walkabout" tests used this
FREQ=144.392929		# Tests in VVille, after St. Louis, and with replacement board xmitting 1229 Hz too high
#FREQ=144.390		# Did *NOT* get decoded on direwolf...
#FREQ=144.3941		# CF with 0.100 divider may spread the inter-grouping signals out more like the real/live signals appear - St. Louis tests used this!

cd /home/pifm

while [ 1 ]
do
	/home/pifm/makePacket.sh -q >/dev/null

	## Play packet (wav) file out via BCM built-in oscillator
	##/home/pifm/pifm /home/pifm/packet.Loc.wav ${FREQ} 44100 mono 4 2>&1 > /dev/null

	## Play packet (wav) file out the PCM0/PCM1 audio output (feeds the Baofeng 888 microphone input)
	##/usr/bin/aplay /home/pifm/packet.Loc.wav 2>&1 > /dev/null

	# Give packet to Direwolf's "kissutil"
	##tail -1 z.txt > /home/direwolf/outbox/z.txt
	cp z.txt /home/direwolf/outbox

	## LIVE VALUE -
	##sleep 43 # Warpig-III value
	##sleep 53 # Warpig-IV value
	##sleep 97 # Warpig-V value
	##sleep 97 # Warpig-VI value
	sleep 97 # Warpig-VII value

	## TEST VALUE (SHORT) -
	##sleep 11

	## TEST VALUE (LOOOOOOOOONNNNNG) -
	#sleep 193	# 3 minutes and 13 seconds
	#sleep 251	# 4 minutes and 11 seconds
	#sleep 293	# A few seconds shy of 5 minutes

done

exit 0

